const DataRegis = [
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "Leo Krisnoto",
        email: "leo@gmail",
        phoneNumber: "08123456789",
        status: "active",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "himawan fauzi",
        email: "hima.one@gmail",
        phoneNumber: "08123456789",
        status: "inactive",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "krisna ardhian",
        email: "ntis@gmail",
        phoneNumber: "08123456789",
        status: "active",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "karyadi sahputra",
        email: "nfree@gmail",
        phoneNumber: "08123456789",
        status: "inactive",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "putra bernanto",
        email: "bernanto@gmail",
        phoneNumber: "08123456789",
        status: "active",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "Leo Krisnoto",
        email: "leo@gmail",
        phoneNumber: "08123456789",
        status: "active",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "himawan fauzi",
        email: "hima.one@gmail",
        phoneNumber: "08123456789",
        status: "inactive",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "krisna ardhian",
        email: "ntis@gmail",
        phoneNumber: "08123456789",
        status: "active",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "karyadi sahputra",
        email: "nfree@gmail",
        phoneNumber: "08123456789",
        status: "inactive",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "putra bernanto",
        email: "bernanto@gmail",
        phoneNumber: "08123456789",
        status: "active",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "Leo Krisnoto",
        email: "leo@gmail",
        phoneNumber: "08123456789",
        status: "active",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "himawan fauzi",
        email: "hima.one@gmail",
        phoneNumber: "08123456789",
        status: "inactive",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "krisna ardhian",
        email: "ntis@gmail",
        phoneNumber: "08123456789",
        status: "active",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "karyadi sahputra",
        email: "nfree@gmail",
        phoneNumber: "08123456789",
        status: "inactive",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "putra bernanto",
        email: "bernanto@gmail",
        phoneNumber: "08123456789",
        status: "active",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "Leo Krisnoto",
        email: "leo@gmail",
        phoneNumber: "08123456789",
        status: "active",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "himawan fauzi",
        email: "hima.one@gmail",
        phoneNumber: "08123456789",
        status: "inactive",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "krisna ardhian",
        email: "ntis@gmail",
        phoneNumber: "08123456789",
        status: "active",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "karyadi sahputra",
        email: "nfree@gmail",
        phoneNumber: "08123456789",
        status: "inactive",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "putra bernanto",
        email: "bernanto@gmail",
        phoneNumber: "08123456789",
        status: "active",
    },   
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "Leo Krisnoto",
        email: "leo@gmail",
        phoneNumber: "08123456789",
        status: "active",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "himawan fauzi",
        email: "hima.one@gmail",
        phoneNumber: "08123456789",
        status: "inactive",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "krisna ardhian",
        email: "ntis@gmail",
        phoneNumber: "08123456789",
        status: "active",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "karyadi sahputra",
        email: "nfree@gmail",
        phoneNumber: "08123456789",
        status: "inactive",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "putra bernanto",
        email: "bernanto@gmail",
        phoneNumber: "08123456789",
        status: "active",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "Leo Krisnoto",
        email: "leo@gmail",
        phoneNumber: "08123456789",
        status: "active",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "himawan fauzi",
        email: "hima.one@gmail",
        phoneNumber: "08123456789",
        status: "inactive",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "krisna ardhian",
        email: "ntis@gmail",
        phoneNumber: "08123456789",
        status: "active",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "karyadi sahputra",
        email: "nfree@gmail",
        phoneNumber: "08123456789",
        status: "inactive",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "putra bernanto",
        email: "bernanto@gmail",
        phoneNumber: "08123456789",
        status: "active",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "Leo Krisnoto",
        email: "leo@gmail",
        phoneNumber: "08123456789",
        status: "active",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "himawan fauzi",
        email: "hima.one@gmail",
        phoneNumber: "08123456789",
        status: "inactive",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "krisna ardhian",
        email: "ntis@gmail",
        phoneNumber: "08123456789",
        status: "active",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "karyadi sahputra",
        email: "nfree@gmail",
        phoneNumber: "08123456789",
        status: "inactive",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "putra bernanto",
        email: "bernanto@gmail",
        phoneNumber: "08123456789",
        status: "active",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "Leo Krisnoto",
        email: "leo@gmail",
        phoneNumber: "08123456789",
        status: "active",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "himawan fauzi",
        email: "hima.one@gmail",
        phoneNumber: "08123456789",
        status: "inactive",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "krisna ardhian",
        email: "ntis@gmail",
        phoneNumber: "08123456789",
        status: "active",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "karyadi sahputra",
        email: "nfree@gmail",
        phoneNumber: "08123456789",
        status: "inactive",
    },
    {
        id: Math.random().toPrecision(10).replace("0.", ""),
        name: "putra bernanto",
        email: "bernanto@gmail",
        phoneNumber: "08123456789",
        status: "active",
    },   
]

export default DataRegis